name: remote-build-tee

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: azure-demo ${{ github.sha }}
      uses: appleboy/ssh-action@v1.0.3
      with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         command_timeout: 120m
         script: |
            git clone https://github.com/tlsnotary/tlsn
            cd tlsn
            git checkout 3554db83e17b2e5fc98293b397a2907b7f023496
            cd crates/notary/server
            /home/ubuntu/.cargo/bin/cargo run --bin notary-server --features attestation 
