name: remote-build-tee

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: azure-demo
      uses: appleboy/ssh-action@v1.0.3
      with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         command_timeout: 120m
         script: |
            git clone https://github.com/tlsnotary/tlsn
            cd tlsn
            git checkout ${{ github.sha }}
            cd crates/notary/server
            cargo run --bin notary-server --features attestation 
